apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - dev1
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "dev"
        effect: "NoExecute"

      volumeMounts:
        - name: website-content
          mountPath: /usr/local/apache2/htdocs/
    volumes:
      - name: website-content
        configMap:
          name: my-website-html
