apiVersion: v1
kind: Service
metadata:
  name: LoadBalancer
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 82
      targetPort: 80
  #clusterIP: 10.0.171.239
  type: LoadBalancer