apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
namespace: ns-01  
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "dev"
    effect: "NoExecute"    
