global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (host metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.31.13.4:9100']

  # Grafana metrics (ONLY if enabled in grafana.ini or docker env)
  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.31.10.150:3000']
