apiVersion: v1
kind: Pod
metadata:
  name: logesh
  labels:
    app: dev  
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: nginx-port

  - name: tomcat
    image: tomcat:latest
    ports:
      - containerPort: 8080
        name: tomcat-port
---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  selector:
    app: dev
  ports:
  - name: nginx-service
    protocol: TCP
    port: 80
    targetPort: nginx-port
  - name: tomcat-service
    protocol: TCP
    port: 8080
    targetPort: tomcat-port
